---

name: Benchmark xmlupload

on:
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: read

jobs:
  benchmark:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout dsp-tools repo
        uses: actions/checkout@v4
      - name: Install uv, just, and dependencies
        uses: ./.github/actions/setup
      - name: Install Podman
        run: |
          curl -fsSL -o podman-linux-amd64.tar.gz https://github.com/mgoltzsche/podman-static/releases/latest/download/podman-linux-amd64.tar.gz
          tar -xzf podman-linux-amd64.tar.gz
          sudo cp -r podman-linux-amd64/usr podman-linux-amd64/etc /
      - name: Install podman-compose
        run: uv add podman-compose
      - name: Versions of podman and podman-compose
        run: |
          podman --version
          .venv/bin/podman-compose --version
      - name: benchmark xmlupload
        run: uv run scripts/benchmark_xmlupload.py

